---
- name: add hosts
  hosts: k8s
  become: yes
  tasks:
    - lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        create: yes
      with_items:
        - '192.168.31.70 k8s01'
        - '192.168.31.232 k8s02'
        - '192.168.31.231 k8s03'