---
- name: 002 install keepalived master
  hosts: k8s01
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: keepalived
        state: latest
    - copy: 
        src: ./keepalived.conf
        dest: /home/charles
    - shell: cat /home/charles/keepalived.conf > /etc/keepalived/keepalived.conf
    - systemd:
        name: keepalived
        state: restarted

- name: 002 install keepalived backup
  hosts: k8s02
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: keepalived
        state: latest
    - copy: 
        src: ./keepalived.conf
        dest: /home/charles
    - shell: cat /home/charles/keepalived.conf > /etc/keepalived/keepalived.conf
    - replace:
        path: /etc/keepalived/keepalived.conf
        regexp: 'MASTER'
        replace: 'BACKUP'
    - systemd:
        name: keepalived
        state: restarted