---
- name:
  hosts: k8s
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: {{item}}
        state: latest
      with_item:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - software-properties-common

- name:
  hosts: k8s
  become: yes
  tasks:
    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - apt_repository:
        repo: " https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu stable"
