---
- name:
  hosts: k8s
  become: yes
  roles:
    - common

- name:
  hosts: k8s01
  become: yes
  roles:
    - keepalived-master

- name:
  hosts: k8s02
  become: yes
  roles:
    - keepalived-backup

#- name:
#  hosts: k8s01,k8s02
#  become: yes
#  roles:
#    - haproxy