---
- name:
  hosts: k8s
  become: yes
  roles:
    - 000-common

- name:
  hosts: k8s01
  become: yes
  roles:
    - 010-keepalived-master

- name:
  hosts: k8s02
  become: yes
  roles:
    - 011-keepalived-backup

- name:
  hosts: k8s01,k8s02
  become: yes
  roles:
    - 020-haproxy

- name: 
  hosts: k8s
  become: yes
  roles:
    - 030-docker

- name: 
  hosts: k8s
  become: yes
  roles: 
    - 040-kubeadm

- name:
  hosts: k8s01
  become: yes
  roles:
    - 050-k8s-master

- name:
  hosts: k8s02,k8s03
  become: yes
  roles:
    - 051-k8s-node
