---
# tasks file for 030-docker
- name:
    apt: update_cache=yes name={{item}} state=latest
    with_item:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'

- name:
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    apt_repository: repo="https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu stable"
    apt: update_cache=yes name=docker-ce=18.06.2~ce~3-0~ubuntu state=present

- name:
    template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    file: path=/etc/systemd/system/docker.service.d state=directory
  notify: restart docker

- name:
    systemd: name=docker daemon-reload=yes
    systemd: name=docker state=started