---
- name: install haproxy
  apt: update_cache=yes name=haproxy state=latest

- name: 
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy

- name: start haproxy
  service: name=haproxy state=started